name: Update Scottish Football Stats

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allows manual trigger
  
jobs:
  update_stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v8
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Kotlin
        run: sudo apt-get install -y kotlin

      - name: Build the project
        run: ./gradlew build

      - name: Run Kotlin script
        env:
          API_KEY: ${{ secrets.API_FOOTBALL_KEY }}
        run: kotlin .github/scripts/UpdateStats.kts
