name: Update Scottish Football Stats

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Kotlin
        uses: fwilhe2/setup-kotlin@main
        with:
          version: '1.8.0'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq

      - name: Fetch and update stats
        env:
          API_KEY: ${{ secrets.API_FOOTBALL_KEY }}
        run: |
          kotlin .github/scripts/UpdateStats.kt